# Nth Prime

Welcome to Nth Prime on Exercism's Python Track.
If you need help running the tests or submitting your code, check out `HELP.md`.

## Instructions

Given a number n, determine what the nth prime is.

By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.

If your language provides methods in the standard library to deal with prime numbers, pretend they don't exist and implement them yourself.

## Exception messages

Sometimes it is necessary to [raise an exception](https://docs.python.org/3/tutorial/errors.html#raising-exceptions). When you do this, you should always include a **meaningful error message** to indicate what the source of the error is. This makes your code more readable and helps significantly with debugging. For situations where you know that the error source will be a certain type, you can choose to raise one of the [built in error types](https://docs.python.org/3/library/exceptions.html#base-classes), but should still include a meaningful message.

This particular exercise requires that you use the [raise statement](https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement) to "throw" a `ValueError` when the `prime()` function receives malformed input. Since this exercise deals only with _positive_ numbers, any number < 1 is malformed.  The tests will only pass if you both `raise` the `exception` and include a message with it.

To raise a `ValueError` with a message, write the message as an argument to the `exception` type:

```python
# when the prime function receives malformed input
raise ValueError('there is no zeroth prime')
```

## Source

### Created by

- @sjakobi

### Contributed to by

- @behrtam
- @BethanyG
- @cmccandless
- @Dog
- @ikhadykin
- @jandersoncampelo
- @kytrinyx
- @N-Parsons
- @pheanex
- @robkeim
- @smalley
- @tqa236
- @yawpitch

### Based on

A variation on Problem 7 at Project Euler - https://projecteuler.net/problem=7